# Generated by Django 3.0 on 2020-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
