# Generated by Django 3.0 on 2020-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0002_city_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
