# Generated by Django 3.0 on 2020-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0003_auto_20200714_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=50)),
                ('remail', models.CharField(max_length=100)),
                ('rphone', models.IntegerField()),
                ('rreview', models.CharField(max_length=1000)),
            ],
        ),
    ]
