# Generated by Django 3.0 on 2020-07-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.CharField(max_length=150)),
                ('cphone', models.IntegerField()),
                ('cquery', models.CharField(max_length=1500)),
            ],
        ),
    ]
